/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed": "#0b1c30",
        "surface": "#f7f9fb",
        "primary": "#000000",
        "on-tertiary-container": "#75859d",
        "primary-container": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "secondary-container": "#d5e3fd",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#38485d",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-container-highest": "#e0e3e5",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#bec6e0",
        "on-secondary-container": "#57657b",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#d5e3fd",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#e6e8ea",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#0d1c2f",
        "surface-tint": "#565e74",
        "on-primary-fixed": "#131b2e",
        "secondary": "#515f74",
        "tertiary-container": "#0b1c30",
        "primary-fixed-dim": "#bec6e0",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-surface": "#191c1e",
        "tertiary": "#000000",
        "on-secondary-fixed-variant": "#3a485c",
        "on-primary-container": "#7c839b",
        "outline": "#76777d",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "tertiary-fixed": "#d3e4fe"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-md": "16px",
        "unit": "8px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-lg": "32px",
        "stack-xs": "4px",
        "stack-xl": "64px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "headline-xl": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
